FROM rust:alpine as builder
RUN apk add musl-dev
RUN rustup default nightly
WORKDIR /app
COPY cardinal-rs .
RUN RUSTFLAGS="-Zon-broken-pipe=kill" cargo build --release

FROM scratch
COPY --from=builder /app/target/release/ocdscardinal /
ENTRYPOINT ["./ocdscardinal"]
